import type { Metadata } from "next";
import { Inter, Kalnia } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-default",
  subsets: ["latin"],
});

const kalnia = Kalnia({
  variable: "--font-title",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "BookFinder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${kalnia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
